# navigation_params.yaml

controller_server:
  ros__parameters:
    use_sim_time: True

planner_server:
  ros__parameters:
    planner_plugins: ["nav2_navfn_planner/NavfnPlanner"]
    use_sim_time: True

bt_navigator:
  ros__parameters:
    use_sim_time: True

costmap:
  ros__parameters:
    global_frame: "map"
    robot_base_frame: "base_link"
    static_map: false
    rolling_window: true
    width: 10.0
    height: 10.0
    resolution: 0.05
    plugins:
      - name: "nav2_costmap_2d/StaticLayer"
        type: "nav2_costmap_2d::StaticLayer"
        ros__parameters:
          map_topic: "map"
      - name: "nav2_costmap_2d/ObstacleLayer"
        type: "nav2_costmap_2d::ObstacleLayer"
        ros__parameters:
          observation_sources: laser_scan_sensor
          laser_scan_sensor: {sensor_frame: "laser_frame", data_type: "LaserScan", topic: "scan", marking: true, clearing: true}
